name: "GPG (Cron)"

on:
  schedule:
    - cron: '0 */6 * * *'

env:
  domain: "${{ github.server_url }}"
  repo: "${{ github.repository }}"

jobs:
  build:
    runs-on: ubuntu-latest
    name: "Build"
    env:
      gpg_url: "https://dl.xanmod.org/gpg.key"
      gpg_name: "apt.xanmod.gpg"
      gpg_cmd: "dearmor"
    steps:
      - uses: ghastore/gpgstore-gpg-build@main
        with:
          git_repo: "${{ env.domain }}/${{ env.repo }}.git"
          git_user: "${{ secrets.BOT_GITHUB_NAME }}"
          git_email: "${{ secrets.BOT_GITHUB_EMAIL }}"
          git_token: "${{ secrets.BOT_GITHUB_TOKEN }}"
          gpg_url: "${{ env.gpg_url }}"
          gpg_name: "${{ env.gpg_name }}"
